### PR TITLE
Configuration

### PR DESCRIPTION
**Pull request by boreq**

### CODE REVIEW

**Comment by boreq** [comment]
@cooldracula does this work: https://github.com/planetary-social/nos-notification-service-go/blob/configuration/README.md ?

**Comment by cooldracula** [comment]
> @cooldracula does this work: https://github.com/planetary-social/nos-notification-service-go/blob/configuration/README.md ?

Love that this is just using environment variables and results in a static binary.  It simplifies the deployment and makes it more flexible.

I wasn't able to try out the local development (signed up for an apple developer account, but need to be a part of a program or an organisation's program to be able to make certificates), but walked through the code and it looks simple and clean.  I just had a couple questions, posted above.

To double-check, to deploy we would need:
- the binary
- the apns certificate on a local path
- the firestone credentials on a local path
- our env vars (e.g. in an .envrc file)

Does that sound correct?
If so, we probably don't have to use a docker image at all.  We could deploy the binary to an ubuntu server and then utilize systemd to make sure it stays up and running.  That could simplify deployment even more.

**Comment by boreq** [comment]
> I wasn't able to try out the local development (signed up for an apple developer account, but need to be a part of a program or an organisation's program to be able to make certificates), but walked through the code and it looks simple and clean. I just had a couple questions, posted above.

Yeah I can make an APNs cert for you but I also checked that a "production" config works locally (certs load correctly, we can establish Firestore connection correctly etc). I don't know who is able to add you to the org, probably @mplorentz or @rabble.
 
> To double-check, to deploy we would need:
> 
> * the binary
> * the apns certificate on a local path
> * the firestone credentials on a local path
> * our env vars (e.g. in an .envrc file)

Yes. I need to double-check that the way I want to auth with Firestore is the correct way to do it though.

>If so, we probably don't have to use a docker image at all. We could deploy the binary to an ubuntu server and then utilize systemd to make sure it stays up and running. That could simplify deployment even more.

Sure, I added a Dockerfile in case we want to make sure that the builds can just happen inside of a container and don't require installing anything else as long as Docker/Podman/etc is available. I thought that maybe that is easier.

**Comment by mplorentz** [comment]
(for posterity: I added @cooldracula to the Apple Developer account yesterday)

**Pull request merged**
